# Generated by Django 2.0.1 on 2018-03-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='diseaseLink',
            new_name='symptom',
        ),
    ]
