# Generated by Django 2.0.1 on 2018-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='concept_type',
            field=models.CharField(default='Null', max_length=150, null=True),
        ),
    ]
