# Generated by Django 2.0.1 on 2018-03-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20180306_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='symptom',
            new_name='disease_link',
        ),
    ]
