# Generated by Django 2.0.1 on 2018-02-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20180221_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='value',
            unique_together=set(),
        ),
    ]
