# Generated by Django 2.0.1 on 2018-01-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Property_describe',
            new_name='property_describe',
        ),
        migrations.AddField(
            model_name='user',
            name='add_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='add_at',
            field=models.DateTimeField(),
        ),
    ]
