# Generated by Django 2.0.1 on 2018-01-25 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_agree', models.IntegerField()),
                ('count_disagree', models.IntegerField()),
                ('is_valid', models.BooleanField()),
                ('disease', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='newhub.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_describe', models.CharField(max_length=250)),
                ('count_editor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_email', models.CharField(max_length=250, unique=True)),
                ('user_organization', models.CharField(max_length=250)),
                ('user_password', models.CharField(max_length=250)),
                ('is_related', models.BooleanField()),
                ('is_doctor', models.BooleanField()),
                ('add_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_at', models.DateTimeField()),
                ('DiseaseLink', models.ManyToManyField(to='newhub.DiseaseLink')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhub.Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhub.User')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_detail', models.CharField(max_length=250)),
                ('count_editor', models.IntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhub.Disease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhub.Property')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhub.Symptom')),
            ],
        ),
        migrations.AddField(
            model_name='userlog',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhub.Value'),
        ),
        migrations.AddField(
            model_name='property',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhub.Symptom'),
        ),
        migrations.AddField(
            model_name='diseaselink',
            name='symptom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='newhub.Symptom'),
        ),
        migrations.AlterUniqueTogether(
            name='diseaselink',
            unique_together={('disease', 'symptom')},
        ),
    ]
